# Generated by Django 2.2.4 on 2020-03-09 02:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bingo', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='assign_randomly',
            field=models.BooleanField(default=True),
        ),
    ]
