# Generated by Django 2.2.4 on 2020-03-09 20:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bingo', '0002_auto_20200309_1816'),
    ]

    operations = [
        migrations.CreateModel(
            name='Guess',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bingo.Question')),
                ('board', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bingo.Board')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bingo.QuestionInQueue')),
            ],
        ),
    ]
