# Generated by Django 2.2.4 on 2020-03-09 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bingo', '0003_guess'),
    ]

    operations = [
        migrations.AddField(
            model_name='board',
            name='score',
            field=models.IntegerField(default=10),
        ),
    ]
