# Generated by Django 2.2.4 on 2020-03-09 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bingo', '0004_board_score'),
    ]

    operations = [
        migrations.AddField(
            model_name='board',
            name='cols',
            field=models.IntegerField(default=5),
        ),
        migrations.AddField(
            model_name='board',
            name='rows',
            field=models.IntegerField(default=5),
        ),
    ]
