# Generated by Django 2.2.4 on 2020-03-10 00:19

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bingo', '0005_auto_20200309_2123'),
    ]

    operations = [
        migrations.AddField(
            model_name='queue',
            name='start_time',
            field=models.DateTimeField(default=datetime.datetime(1970, 1, 1, 0, 0)),
        ),
        migrations.AddField(
            model_name='queue',
            name='wait_per_question',
            field=models.DurationField(default=datetime.timedelta(0, 43200)),
        ),
    ]
